version: '2'
services:
  photon:
    build:
      context: .
      dockerfile: Dockerfile
    image: moritz2k927/photon-docker
    volumes:
      - ./data:/photon/photon_data
    ports:
      - 2322:2322

volumes:
  data:
    driver: local
