version: '2'
services:
  photon:
    build:
      context: .
      dockerfile: Dockerfile
    image: moritz2k/photon-docker
    volumes:
      - ./photon_data:/photon/photon_data
    ports:
      - 2322:2322

volumes:
  photon_data:
    driver: local
